### ISSUE TITLE
@umijs/plugin-locale下拉选择时报[antd: Menu] `children` will be removed in next major version. Please use `items` instead. 

### ISSUE THREAD

**Issue by kakuilan** [umijs/plugins#850]
如题，在ant design pro切换语言时，提示
```txt
devScripts.js:6523 Warning: [antd: Menu] `children` will be removed in next major version. Please use `items` instead. 
    at http://localhost:8000/mf-dep_vendors-node_modules_antd_es_menu_index_js.8f3ead17.async.js:999:62
    at Menu (http://localhost:8000/mf-dep_vendors-node_modules_antd_es_menu_index_js.8f3ead17.async.js:1084:87)
    at div
    at Align (http://localhost:8000/mf-dep_vendors-node_modules_rc-trigger_es_index_js.f5d98dad.async.js:1452:23)
    at DomWrapper (http://localhost:8000/mf-dep_vendors-node_modules_rc-motion_es_index_js.a9369a59.async.js:375:87)
    at http://localhost:8000/mf-dep_vendors-node_modules_rc-motion_es_index_js.a9369a59.async.js:61:32
    at http://localhost:8000/mf-dep_vendors-node_modules_rc-trigger_es_index_js.f5d98dad.async.js:1921:23
    at div
    at http://localhost:8000/mf-dep_vendors-node_modules_rc-trigger_es_index_js.f5d98dad.async.js:2157:22
    at http://localhost:8000/mf-dep_vendors-node_modules_rc-trigger_es_index_js.f5d98dad.async.js:3414:25
    at Trigger (http://localhost:8000/mf-dep_vendors-node_modules_rc-trigger_es_index_js.f5d98dad.async.js:2455:89)
    at Dropdown (http://localhost:8000/mf-dep_vendors-node_modules_ant-design_icons_es_icons_EllipsisOutlined_js-node_modules_rc-dropdown_e-110fbb.3e09dd1e.async.js:81:28)
    at Dropdown (http://localhost:8000/mf-dep_vendors-node_modules_antd_es_dropdown_dropdown-button_js-node_modules_antd_es_dropdown_dropdown_js.8ba469a4.async.js:219:62)
    at HeaderDropdown (http://localhost:8000/umi.js:2309:18)
    at SelectLang (http://localhost:8000/umi.js:2667:35)
```

版本:
- ant design pro  [5.2.0]
- umi [^3.5.0]

**Comment by shurong2199** [comment]
确实有此问题

**Comment by shurong2199** [comment]
具体为 Umi Max 4  <SelectLang /> 组件

**Comment by shurong2199** [comment]
具体为 Umi Max 4 的 SelectLang 组件
